# Spring debug output
debug: false

# Global and app logging level
logging:
  path: logs/
  level:
    root: info
    com:
      krzyszkowski:
        yggdrasil: info

# API endpoint URLs
dataproviders:
  openweathermap:
    endpoint: http://api.openweathermap.org/data/2.5/weather
  newsapi:
    endpoint: https://newsapi.org/v2/top-headlines
  translate:
    endpoint: https://translate.yandex.net/api/v1.5/tr.json/translate
